<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $events = [
            [
                'id' => 1,
                'banner_01' => ['events/banner/01JKQ7BJWCGQM4W3CPD6JZNVT3.jpg'],
                'title' => 'Boda <span class="text-2xl lg:text-4xl">Donde los sueños encuentran su escenario perfecto</span>',
                'slug' => 'bodas',
                'img_event_type_01' => 'events/event-type/01JKPA6KK4RQA03WY7CWD0XFYW.jpg',
                'title_event_type_01' => 'BODAS CIVILES',
                'img_event_type_02' => 'events/event-type/01JMNGS8BX8C5DABBZEF33SY8K.jpg',
                'title_event_type_02' => 'BODAS RELIGIOSAS',
                'title_service' => 'En Cajamarca cada boda es <strong class="italic"> única y especial</strong>',
                'image_service_01' => 'events/service/01JKPF7GAKGQRXJ2YNHH5REQ47.jpg',
                'title_service_01' => 'Espacios diseñados para bodas únicas',
                'content_service_01' => 'Cada rincón ha sido cuidadosamente creado para ofrecer el escenario perfecto para tu boda. Desde jardines exuberantes hasta salones elegantes, cada espacio se adapta a tus necesidades y deseos, brindando un ambiente exclusivo y encantador. Aquí, la naturaleza y la arquitectura se fusionan para crear un marco inolvidable para tu día especial.',
                'image_service_02' => 'events/service/01JKPF7GB434QNRBV8D76181GQ.jpg',
                'title_service_02' => 'Atención personalizada',
                'content_service_02' => 'En Cajamarca, entendemos que cada boda es una historia única, y nos enorgullece ofrecer un servicio a la medida. Nuestro equipo experto te acompaña en cada paso, desde la planificación hasta la ejecución, asegurándose de que cada detalle refleje tu visión y estilo. Estamos comprometidos a hacer realidad tus sueños, brindando una atención cálida y dedicada.',
                'image_service_03' => 'events/service/01JKPF7GB7S519JHPJE42D83TS.jpg',
                'title_service_03' => 'Experiencia gastronómica',
                'content_service_03' => 'La gastronomía es una parte fundamental de la experiencia en Cajamarca. Nuestro Chef Internacional combina ingredientes frescos y locales para crear un menú personalizado que deleitará a tus invitados. Cada plato es una obra de arte culinaria que complementa la magia de tu boda, haciendo que cada bocado sea tan memorable como el resto de tu celebración.',
                'title_space' => 'Explora nuestros <strong class="italic block"> encantadores espacios</strong>',
                'image_space_01' => 'events/spapce/01JKPFDEKQXD05G9HFM8J674HS.jpg',
                'title_space_01' => 'Jardines',
                'content_space_01' => 'Nuestros jardines ofrecen un oasis de paz con flores vibrantes y paisajes naturales, perfectos para ceremonias al aire libre y momentos de ensueño.',
                'image_space_02' => 'events/spapce/01JKPFDEKTG01ZPZ3Q80DK5T7Q.jpg',
                'title_space_02' => 'Bosques',
                'content_space_02' => 'Sumérgete en la serenidad de nuestros bosques, un entorno mágico donde la naturaleza se convierte en el escenario ideal para tu celebración.',
                'image_space_03' => 'events/spapce/01JKPFDEKXN4EAGD7EBSNERNYH.jpg',
                'title_space_03' => 'Capilla',
                'content_space_03' => 'La capilla Nuestra Señora del Carmen, es un santuario íntimo y solemne, donde la espiritualidad y el amor se unen en una atmósfera encantadora.',
                'image_space_04' => 'events/spapce/01JKPFDEKZ67NN2BTFYHTFWTFQ.jpg',
                'title_space_04' => 'Salones',
                'content_space_04' => 'Nuestros salones versátiles y elegantes se adaptan a cualquier tipo de evento, ofreciendo comodidad y sofisticación en cada detalle.',
                'image_space_05' => 'events/spapce/01JKPFDEM2WCYYQMXBHV2XDAYR.png',
                'title_space_05' => 'Villas',
                'content_space_05' => 'Disfruta de una estancia inolvidable en nuestras villas boutique, un refugio lujoso que combina comodidad y estilo en cada rincón.',
                'image_space_06' => 'events/spapce/01JKPFDEM7EHCSNKRYW3FG5K1Y.jpg',
                'title_space_06' => 'Bistró',
                'content_space_06' => 'El Bistró de Cajamarca es un rincón culinario donde la tradición y la innovación se encuentran, ofreciendo una experiencia gastronómica única y acogedora.',
                'image_description_01' => 'events/description/01JKQ0QASYEFNA07266GRY2CQC.jpg',
                'title_description' => 'Cajamarca, un lugar donde los sueños se entrelazan en un <strong class="italic">sí, acepto</strong>',
                'content_description' => '<p>En Cajamarca, cada boda se transforma en una celebración inolvidable, donde la naturaleza y el amor se entrelazan para crear momentos eternos. Nuestros jardines exuberantes y la arquitectura colonial ofrecen el escenario perfecto para un día especial.</p><p>Desde la ceremonia hasta el último baile, cuidamos cada detalle para reflejar la esencia de los novios y crear una experiencia personalizada. Con un equipo dedicado, hacemos que cada boda en Cajamarca sea tan única como el amor que celebran.</p>',
                'title_gallery' => 'GALERIA',
                'images_gallery_01' => ["events/gallery/01JKPYH12DENYAD8BTNK8869FC.jpg","events/gallery/01JKPYH12SYAANKJAW42P4FZ8H.jpg","events/gallery/01JKPYH132059H8B0F408GW6TS.jpg","events/gallery/01JKPYH138Y7BZ94MA93FB828S.jpg","events/gallery/01JKPYH13FNMTJ52HRTEK6G5R0.jpg","events/gallery/01JKPYH13KWRVFRZ1F22TMC3HD.jpg","events/gallery/01JKPYH13R66ACGKRZNQ6D4FBG.jpg","events/gallery/01JKPYH13WP3DZ1ZRS6GAZ7BFQ.jpg","events/gallery/01JKPYH142KMQ4BG7Y6B3VKRAM.jpg","events/gallery/01JKPYH14806HVP6J2GMX59WC2.jpg","events/gallery/01JKPYH14BSWXK7MPQEV84KPZ2.png","events/gallery/01JKPYH14Q3GC9QHBGZ1YWVDTR.jpg","events/gallery/01JKPYH14YGNYJNCZT6HEM9Z5K.jpg","events/gallery/01JKPYH155HHGTWAF5ZKCZ0VA3.jpg"],

                'title_form'=> '¡Cotiza tu evento ahora!',
                'quoter_destination'=> 'luisa.jimenez@cajamarcasal.com',

                'title_seo' => 'Bodas',
                'description_seo' => 'En Cajamarca, cada boda se transforma en una celebración inolvidable, donde la naturaleza y el amor se entrelazan para crear momentos eternos.',
                'keywords_seo' => 'Boda, evento, casamientos, evento social',
                'image_seo' => 'events/seo/01JKPJ69AEK1Q98BSJRW0AQP40.jpg',
                'created_at' => '2025-02-09 21:33:03',
                'updated_at' => '2025-02-10 06:20:36',
            ],
            [
                'id' => 2,
                'banner_01' => ['events/banner/01JKQ31F95EV9F1FYEDAMYRXHS.jpg'],
                'title' => 'Eventos <span>SOCIALES</span> <span class="text-2xl lg:text-4xl">Vive tus celebraciones en el volcán de San Salvador</span>',
                'slug' => 'eventos-sociales',
                'img_event_type_01' => 'events/event-type/01JKQ1H8X2NJTNQ0PRGNB6P5FQ.png',
                'title_event_type_01' => 'GRADUACIONES',
                'img_event_type_02' => 'events/event-type/01JKQ1H8X86D32WFRTE6T2B3JB.jpg',
                'title_event_type_02' => 'PRIMERAS COMUNIONES',
                'img_event_type_03' => 'events/event-type/01JKQ1H8XDS2X9X89CVGHYZC57.jpg',
                'title_event_type_03' => 'BAUTIZOS',
                'img_event_type_04' => 'events/event-type/01JKQ1H8XJK9VC0VFG0YWQGH89.jpg',
                'title_event_type_04' => 'BABY SHOWER',
                'img_event_type_05' => 'events/event-type/01JKQ1H8XQ67Q46KNZ5XWSAPRG.jpg',
                'title_event_type_05' => 'GENDER REVEAL',
                'img_event_type_06' => 'events/event-type/01JKQ1H8Y69GR2XZ1CAW24BJMQ.jpg',
                'title_event_type_06' => 'CUMPLEAÑOS',
                'img_event_type_07' => 'events/event-type/01JKQ1H8YBBCRJQ2F19BMBTKJY.jpg',
                'title_event_type_07' => 'ANIVERSARIO',
                'img_event_type_08' => 'events/event-type/01JKQ1H8YF9TZEBPJXBZCQNZ55.jpg',
                'title_event_type_08' => '15 AÑOS',
                'title_service' => 'En Cajamarca cada celebración  es única y especial',
                'image_service_01' => 'events/service/01JKQ2981V3JCK653EXJPSXEA5.jpg',
                'title_service_01' => 'Celebraciones entre la naturaleza del volcán de San Salvador',
                'content_service_01' => 'En Cajamarca, cada celebración se rodea de la majestuosidad natural del Volcán de San Salvador, creando un ambiente único y cautivador. Los jardines y bosques ofrecen un telón de fondo que enaltece la belleza de cada momento especial. Aquí, la naturaleza no solo acompaña, sino que eleva la experiencia, haciendo de tu evento algo verdaderamente inolvidable.',
                'image_service_02' => 'events/service/01JKQ2981YMKRYPWDQ3DP8RTKS.jpg',
                'title_service_02' => 'Experiencia gastronómica',
                'content_service_02' => 'Nuestro enfoque en la gastronomía va más allá de ofrecer un menú, es una experiencia culinaria diseñada para deleitar todos los sentidos. Cada plato está elaborado con ingredientes frescos y locales. Desde banquetes grandes hasta comidas íntimas, nuestra cocina aporta un toque especial a cada celebración.',
                'image_service_03' => 'events/service/01JKQ29822VAWSWBA15T28CDGA.jpg',
                'title_service_03' => 'Atención personalizada',
                'content_service_03' => 'En Cajamarca, nos enorgullece ofrecer una atención meticulosa y personalizada a cada uno de nuestros clientes. Desde el primer contacto hasta el final del evento, nuestro equipo está enfocado en hacer realidad tus deseos y necesidades. Creemos que cada detalle cuenta, y trabajamos incansablemente para que cada celebración sea única, especial y sin preocupaciones.',
                'title_space' => 'Explora nuestras instalaciones para eventos sociales',
                'image_space_01' => 'events/spapce/01JKQ2FM7E8PWB52RV94HZ3F0E.jpg',
                'title_space_01' => 'JARDINES',
                'content_space_01' => 'Nuestros jardines ofrecen un oasis de paz con flores vibrantes y paisajes naturales, perfectos para ceremonias al aire libre y momentos de ensueño.',
                'image_space_02' => 'events/spapce/01JKQ32NAZWC2NPMTMATTCMK8B.jpg',
                'title_space_02' => 'BOSQUES',
                'content_space_02' => 'Sumérgete en la serenidad de nuestros bosques, un entorno mágico donde la naturaleza se convierte en el escenario ideal para tu celebración.',
                'image_space_03' => 'events/spapce/01JKQ2FM7N4Z9GDK5K6P3RACEA.jpg',
                'title_space_03' => 'SALONES',
                'content_space_03' => 'La capilla Nuestra Señora del Carmen, es un santuario íntimo y solemne, donde la espiritualidad y el amor se unen en una atmósfera encantadora.',
                'image_description_01' => 'events/description/01JKQ3PCYT8FWR054TDQRYTC48.jpg',
                'title_description' => 'Eventos entre la naturaleza del volcán de San Salvador',
                'content_description' => 'En Cajamarca, cada evento se vive en un entorno único, rodeado por la naturaleza del Volcán de San Salvador y los cafetales que nos rodean. La frescura de los jardines y la tranquilidad de los bosques crean el escenario perfecto para cualquier ocasión especial. Celebra en medio de paisajes cautivadores, donde cada rincón cuenta una historia.',
                'title_gallery' => 'GALERIA',
                'images_gallery_01' => ["events/gallery/01JKQ3WF0CB6Y206010DN4G82A.jpg","events/gallery/01JKQ3WF0NX1QTW3ZC04BS00C6.jpg","events/gallery/01JKQ3WF0V680TP060TYTWSA9V.jpg","events/gallery/01JKQ3WF11H0VVE10WYNWJ8R7Q.jpg","events/gallery/01JKQ3WF1B1YEJBCYJPAMKE0MQ.jpg","events/gallery/01JKQ3WF1J9MTQ8PKD9NAFPN3B.jpg","events/gallery/01JKQ3WF1VJ84PGBP8349VZQ91.jpg","events/gallery/01JKQ3WF207H9QYFPQ3PY3WEHE.jpg","events/gallery/01JKQ3WF26VEGECJW7JD1RTS64.jpg","events/gallery/01JKQ3WF2C8FJ18692BJZSP94C.jpg","events/gallery/01JKQ3WF2M6HFKH07BGYJW02H3.jpg","events/gallery/01JKQ3WF2VDGYEQ23KVYGY29ZN.jpg","events/gallery/01JKQ3WF32Z7R5RFH0GC24ZYM0.jpg","events/gallery/01JKQ3WF3AMK0905QMK0FT4A9T.jpg","events/gallery/01JKQ3WF3H5MGEJWJP0XMEJ79S.jpg","events/gallery/01JKQ3WF3TJDK4ERWPZKVGVB23.jpg","events/gallery/01JKQ3WF40EQRVVS8423F3X3GD.jpg","events/gallery/01JKQ3WF4917WH19TAQJDTZDW9.jpg","events/gallery/01JKQ3WF4FZQ8XCNRKEJK3DPD9.jpg","events/gallery/01JKQ3WF4M2QT94FCBHCRXJAKC.jpg","events/gallery/01JKQ3WF4TMNC3JBYWMVRTYH7W.jpg","events/gallery/01JKQ3WF51J9NSW94JQ4ZDK8FX.jpg","events/gallery/01JKQ3WF57Q78X789FGCB20754.jpg"],

                'title_form'=> '¡Cotiza tu evento ahora!',
                'quoter_destination'=> 'luisa.jimenez@cajamarcasal.com',

                'title_seo' => 'Eventos entre la naturaleza del volcán de San Salvador',
                'description_seo' => 'En Cajamarca, cada evento se vive en un entorno único, rodeado por la naturaleza del Volcán de San Salvador y los cafetales que nos rodean.',
                'keywords_seo' => 'Boda, evento social',
                'image_seo' => 'events/seo/01JKQ3WF5D47EYHS6SNCTM28BF.jpg',
                'created_at' => '2025-02-09 23:43:40',
                'updated_at' => '2025-02-10 05:04:03',
            ],
            [
                'id' => 3,
                'banner_01' => ['events/banner/01JKQ5NCT1ZN88J755FWYKF4Q3.jpg'],
                'title' => 'Eventos <span>CORPORATIVOS</span> <span class="text-2xl lg:text-4xl">Conecta y crece en un entorno dinámico y profesional</span>',
                'slug' => 'eventos-corporativos',
                'img_event_type_01' => 'events/event-type/01JKQ5DEN5J0VPJ87JWZZCQE1G.jpg',
                'title_event_type_01' => 'TEAM BUILDING',
                'img_event_type_02' => 'events/event-type/01JKQ5DEN8KTM9GCAQ8RSGJAX9.jpg',
                'title_event_type_02' => 'SEMINARIOS',
                'img_event_type_03' => 'events/event-type/01JKQ5EJHZTK7CCM7K95B7W4JD.jpg',
                'title_event_type_03' => 'CAPACITACIONES',
                'img_event_type_04' => 'events/event-type/01JKQ5F22DYAGB0AY2AZRCABHT.jpg',
                'title_event_type_04' => 'REUNIÓN DE NEGOCIOS',
                'img_event_type_05' => 'events/event-type/01JKQ5NCT7H9Z456JCNZB09A7P.png',
                'title_event_type_05' => 'LANZAMIENTO DE MARCA',
                'img_event_type_06' => 'events/event-type/01JKQ5NCTB8AQ1HNFTX5SDM6C2.jpg',
                'title_event_type_06' => 'FIESTA NAVIDEÑA CORPORATIVA',
                'img_event_type_07' => 'events/event-type/01JKQ5NCTGZ71ZRCAMGF4H8E03.jpg',
                'title_event_type_07' => 'ENTREGA DE PREMIOS O ANIVERSARIO',
                'img_event_type_08' => 'events/event-type/01JKQ5NCTNZSCGPK1D0EWVJVZ9.jpg',
                'title_event_type_08' => 'OTROS EVENTOS CORPORATIVOS',
                'title_service' => 'En Cajamarca cada evento es una <strong> experiencia única</strong>',
                'image_service_01' => 'events/service/01JKQ5TS63GJZQAJK1M0WYP3QX.jpg',
                'title_service_01' => 'Espacios ideales para conectar y crecer',
                'content_service_01' => 'Nuestros versátiles espacios, rodeados de naturaleza y tranquilidad, ofrecen el entorno perfecto para que las ideas fluyan y las conexiones se fortalezcan. Desde reuniones ejecutivas hasta talleres de formación, en Cajamarca encontrarás un ambiente que estimula la creatividad y la colaboración. Aquí, la naturaleza se convierte en tu aliada para potenciar el crecimiento de tu empresa.',
                'image_service_02' => 'events/service/01JKQ5WD5GWBFNH88CWJQ4161C.jpg',
                'title_service_02' => 'Mobiliario y equipo multimedia para el éxito de tu evento',
                'content_service_02' => 'En Cajamarca, nos aseguramos que tu evento cuente con todas las herramientas necesarias para su éxito. Ofrecemos mobiliario cómodo y moderno, además de tecnología multimedia de última generación, ideal para presentaciones y dinámicas de trabajo. Todo está pensado para que tu equipo se concentre en lo importante: alcanzar los objetivos propuestos.',
                'image_service_03' => 'events/service/01JKQ5YGZT6KQTPKSSTE8RJCFS.jpg',
                'title_service_03' => 'Atención personalizada',
                'content_service_03' => 'Entendemos que cada evento corporativo es único, por lo que ofrecemos un servicio totalmente personalizado. Desde el primer contacto hasta el día del evento, nuestro equipo estará a tu disposición para asegurarse de que todo se desarrolle sin contratiempos. Nos enfocamos en cada detalle para que tú puedas concentrarte en lo que realmente importa: el éxito de tu evento.',
                'title_space' => 'Explora nuestras instalaciones para eventos corporativos',
                'image_space_01' => 'events/spapce/01JKQ63MRDGQXSSJDSRA0MG4NT.jpg',
                'title_space_01' => 'JARDINES',
                'content_space_01' => 'Nuestros amplios jardines, rodeados de verde, ofrecen un entorno inspirador para eventos al aire libre, ideales para actividades de integración y dinámicas grupales.',
                'image_space_02' => 'events/spapce/01JKQ63MRHNNE7WZYA7273ESQ2.jpg',
                'title_space_02' => 'BOSQUES',
                'content_space_02' => 'Nuestros amplios jardines, rodeados de verde, ofrecen un entorno inspirador para eventos al aire libre, ideales para actividades de integración y dinámicas grupales.',
                'image_space_03' => 'events/spapce/01JKQ63MRNEKGR6Q3850B4YKYA.jpg',
                'title_space_03' => 'SALONES',
                'content_space_03' => 'Totalmente equipados y con un diseño elegante, nuestros salones están preparados para albergar desde pequeñas reuniones hasta grandes conferencias, asegurando comodidad y éxito en cada evento.',
                'image_description_01' => 'events/description/01JKQ67CM603YGTN7NS0ETVBZW.jpg',
                'title_description' => 'Conecta y crece con tu equipo en un <strong class="italic">entorno único</strong> en el volcán de San Salvador',
                'content_description' => 'En Cajamarca, tu equipo puede conectar y crecer en un entorno único en el volcán de San Salvador, rodeado de cafetales y naturaleza vibrante. Ofrecemos espacios que inspiran colaboración, desde salones equipados hasta jardines y bosques al aire libre. Aquí, las reuniones se transforman en experiencias memorables, donde la serenidad del entorno impulsa nuevas ideas y el éxito del equipo.',
                'title_gallery' => 'GALERIA',
                'images_gallery_01' => ["events/gallery/01JKQ6KHC8T6X0HZEEB7YSHXZG.jpg","events/gallery/01JKQ6KHCFZYRS1NQ9GV460HEC.jpg","events/gallery/01JKQ6KHCNCY0TQ3XC8PKXTNE1.jpg","events/gallery/01JKQ6KHCWA5AGB9QAAQFVNZ4P.jpg","events/gallery/01JKQ6KHD22J4VNP469T8XZ5EP.jpg","events/gallery/01JKQ6KHD8SZCZFRZS13YX9QEM.jpg","events/gallery/01JKQ6KHDDZYM600C4HAD5K9QA.jpg","events/gallery/01JKQ6KHDKFX2JEBZ8PJ95R2Q7.jpg","events/gallery/01JKQ6KHDSFFH55M2AB8PMPFP2.jpg","events/gallery/01JKQ6KHDZJC2YJ2E0QN444HCN.jpg","events/gallery/01JKQ6KHE79BXA77C0PE307DF4.jpg","events/gallery/01JKQ6KHEEQG2R75414B3ETR4F.jpg","events/gallery/01JKQ6KHEN250M4MY40Z99GXMN.jpg","events/gallery/01JKQ6KHESC6WP5K107S78M9GV.jpg","events/gallery/01JKQ6KHEXEAV98Q571HWBV0Y4.jpg"],

                'title_form'=> '¡Cotiza tu evento ahora!',
                'quoter_destination'=> 'luisa.jimenez@cajamarcasal.com',

                'title_seo' => 'Explora nuestras instalaciones para eventos corporativos',
                'description_seo' => 'Conecta y crece con tu equipo en un entorno único en el volcán de San Salvador',
                'keywords_seo' => 'Explora nuestras instalaciones, eventos corporativos, equipo, salones',
                'image_seo' => 'events/seo/01JKQ6ATEBMDK5RKT1QSQARZ64.jpg',
                'created_at' => '2025-02-10 05:30:48',
                'updated_at' => '2025-02-10 05:51:36',
            ],
        ];

        foreach ($events as $event) {
            Event::factory()->create($event);
        }
    }
}
